//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCCStore.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Avaliaco
    {
        public int Id { get; set; }
        public int AlunoId { get; set; }
        public int ProfessorDisciplinaId { get; set; }
        public string Review { get; set; }
        public int NotaGeral { get; set; }
        public int Assiduidade { get; set; }
        public int Didatica { get; set; }
        public int Cobranca { get; set; }
        public int Dominio { get; set; }
    
        public virtual Aluno Aluno { get; set; }
        public virtual ProfessorDisciplina ProfessorDisciplina { get; set; }
    }
}
